begin;

create table if not exists public.news_items (
  id bigint generated by default as identity primary key,
  slug text not null,
  title text not null,
  excerpt text not null default '',
  summary text not null default '',
  source_url text,
  image text,
  image_url text,
  date text,
  published_at timestamptz not null default now(),
  views text,
  view_count integer not null default 0,
  category text not null default 'News',
  is_featured boolean not null default false,
  is_popular boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint news_items_title_not_blank_chk check (char_length(trim(title)) > 0),
  constraint news_items_view_count_non_negative_chk check (view_count >= 0),
  constraint news_items_source_url_chk check (source_url is null or source_url ~* '^https?://'),
  constraint news_items_image_url_chk check (image_url is null or image_url ~* '^https?://')
);

create or replace function public.slugify_uk(value text)
returns text
language plpgsql
immutable
set search_path = ''
as $$
declare
  result text := lower(coalesce(value, ''));
begin
  result := replace(result, 'а', 'a');
  result := replace(result, 'б', 'b');
  result := replace(result, 'в', 'v');
  result := replace(result, 'г', 'h');
  result := replace(result, 'ґ', 'g');
  result := replace(result, 'д', 'd');
  result := replace(result, 'е', 'e');
  result := replace(result, 'є', 'ye');
  result := replace(result, 'ж', 'zh');
  result := replace(result, 'з', 'z');
  result := replace(result, 'и', 'y');
  result := replace(result, 'і', 'i');
  result := replace(result, 'ї', 'yi');
  result := replace(result, 'й', 'y');
  result := replace(result, 'к', 'k');
  result := replace(result, 'л', 'l');
  result := replace(result, 'м', 'm');
  result := replace(result, 'н', 'n');
  result := replace(result, 'о', 'o');
  result := replace(result, 'п', 'p');
  result := replace(result, 'р', 'r');
  result := replace(result, 'с', 's');
  result := replace(result, 'т', 't');
  result := replace(result, 'у', 'u');
  result := replace(result, 'ф', 'f');
  result := replace(result, 'х', 'kh');
  result := replace(result, 'ц', 'ts');
  result := replace(result, 'ч', 'ch');
  result := replace(result, 'ш', 'sh');
  result := replace(result, 'щ', 'shch');
  result := replace(result, 'ь', '');
  result := replace(result, 'ъ', '');
  result := replace(result, 'ы', 'y');
  result := replace(result, 'э', 'e');
  result := replace(result, 'ё', 'yo');
  result := replace(result, 'ю', 'yu');
  result := replace(result, 'я', 'ya');
  result := regexp_replace(result, '[''"`’]', '', 'g');
  result := replace(result, '&', ' and ');
  result := regexp_replace(result, '[^a-z0-9]+', '-', 'g');
  result := regexp_replace(result, '-+', '-', 'g');
  result := trim(both '-' from result);

  if result = '' then
    return 'news';
  end if;

  return result;
end;
$$;

create or replace function public.news_items_set_slug()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  base_slug text;
  candidate_slug text;
  suffix integer := 1;
begin
  base_slug := public.slugify_uk(coalesce(nullif(trim(new.slug), ''), new.title));
  candidate_slug := base_slug;

  while exists (
    select 1
    from public.news_items n
    where n.slug = candidate_slug
      and n.id <> coalesce(new.id, -1)
  ) loop
    suffix := suffix + 1;
    candidate_slug := base_slug || '-' || suffix::text;
  end loop;

  new.slug := candidate_slug;
  return new;
end;
$$;

create or replace function public.news_items_set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_news_items_set_slug on public.news_items;
create trigger trg_news_items_set_slug
before insert or update of slug, title
on public.news_items
for each row
execute function public.news_items_set_slug();

drop trigger if exists trg_news_items_set_updated_at on public.news_items;
create trigger trg_news_items_set_updated_at
before update
on public.news_items
for each row
execute function public.news_items_set_updated_at();

create unique index if not exists news_items_slug_uidx
  on public.news_items (slug);

create index if not exists news_items_published_at_id_idx
  on public.news_items (published_at desc, id desc);

create index if not exists news_items_category_published_idx
  on public.news_items (category, published_at desc, id desc);

create index if not exists news_items_category_ci_published_idx
  on public.news_items (lower(category), published_at desc, id desc);

create index if not exists news_items_view_count_desc_idx
  on public.news_items (view_count desc, id desc);

create index if not exists news_items_featured_published_idx
  on public.news_items (published_at desc, id desc)
  where is_featured = true;

create index if not exists news_items_popular_published_idx
  on public.news_items (published_at desc, id desc)
  where is_popular = true;

create or replace function public.get_news_category_counts()
returns table(category text, count bigint)
language sql
stable
set search_path = ''
as $$
  select
    coalesce(nullif(trim(category), ''), 'News') as category,
    count(*)::bigint as count
  from public.news_items
  group by 1
  order by count(*) desc, 1 asc;
$$;

alter table public.news_items enable row level security;
alter table public.news_items force row level security;

drop policy if exists news_items_public_read on public.news_items;
create policy news_items_public_read
on public.news_items
for select
to anon, authenticated
using (true);

revoke all on function public.slugify_uk(text) from public;
revoke all on function public.news_items_set_slug() from public;
revoke all on function public.news_items_set_updated_at() from public;
revoke all on function public.get_news_category_counts() from public;

revoke all on table public.news_items from public;
revoke all on table public.news_items from anon, authenticated;
grant select on table public.news_items to anon, authenticated;
grant execute on function public.get_news_category_counts() to anon, authenticated;

commit;
